site_name: pstrode
site_description: pstrode 是 pstron 的个人的收集整理 XCPC 算法模板的项目
site_author: pstron
site_url: https://cp.feynmach.com

copyright: 'Copyright &copy; 2026 pstron'

nav:
  - 主页:
      - 欢迎: index.md
      - 打印: intro/print.md
  - 基本:
      - Vim: basic/vim.md
      - C++: basic/cpp.md
  - 数学:
      - 快速幂: math/binpow.md
      - 模逆元: math/modinv.md
  - 数据结构:
      - 并查集: ds/dsu.md
      - ST 表: ds/st.md

theme:
  name: material
  language: 'zh'
  features:
    - content.code.copy
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

plugins:
  - search

markdown_extensions:
  # Tooltips
  - abbr
  # Admonitions
  - admonition
  # Annotations, Buttons, Grids, Icons & Emojis, Images, Tooltips
  - attr_list
  # Footnotes
  - footnotes
  # Annotations, Grids, Images
  - md_in_html
  # Images
  - pymdownx.blocks.caption
  # Formatting
  - pymdownx.caret
  # Formatting
  - pymdownx.critic
  # Admonitions
  - pymdownx.details
  # Icons & Emojis
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # Code Blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  # Code Blocks
  - pymdownx.inlinehilite
  # Formatting
  - pymdownx.keys
  # Formatting
  - pymdownx.mark
  # Code Blocks, Tooltips
  - pymdownx.snippets
  # Admonitions, Annotations, Code Blocks, Content Tabs
  - pymdownx.superfences
  # Content Tabs
  - pymdownx.tabbed:
      alternate_style: true
  # Lists
  - pymdownx.tasklist:
      custom_checkbox: true
  # Formatting
  - pymdownx.tilde
  # Data Tables
  - tables
  # Math
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true

extra:
  generator: false

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@4/tex-mml-chtml.js
